### ISSUE TITLE
Opening the GFI panel causes a visibility error on the Widget map

### ISSUE THREAD

**Issue by ElenaGallo** [geosolutions-it/geonode-mapstore-client#212] opened 2021-03-03 11:20 UTC
Opening the GFI panel causes a visibility error on the Widget map

**How to Reproduce**
- Open [this map](https://master.demo.geonode.org/maps/479/edit)
- Click a fature on map
- Closed the GFI panel

*Current Result*
The position of widgets on the map has changed

**Comment by giohappy** [comment] 2021-03-03 14:36
@ElenaGallo I couldn't reproduce this. Which widgets are you referring to?

![widgets positioning issue](https://user-images.githubusercontent.com/571129/109821341-2a054a00-7c36-11eb-81bf-3f5bd550a0a1.gif)

**Comment by simboss** [comment] 2021-03-03 14:54
@giohappy open the charts, they are closed right now ( see bottom right corner).

Then try the GFI again...

**Comment by simboss** [comment] 2021-03-03 14:55
@ElenaGallo next time you need to describe the exact step, the indicted data/map/whatever and then you might also attache a small video on how to reproduce.

This back and forth is time wasted...

**Comment by ElenaGallo** [comment] 2021-03-03 15:21
@simboss yes, of course.

**Comment by giohappy** [comment] 2021-03-03 16:10
ok, I see now thx.

**Comment by giohappy** [comment] 2021-03-03 16:24
@allyoucanmap now that we have cut 2.1.x if any fix is needed here it will have to be backported on 2.1.x, to be included in GN 3.2

**Comment by allyoucanmap** [comment] 2021-03-04 16:17
@giohappy this issue has been fixed on MapStore2 with this commit https://github.com/geosolutions-it/MapStore2/commit/e5200d2355095a3622b023f99978091f3303982b so we need to update the submodule.
We could update to this commit https://github.com/geosolutions-it/MapStore2/commit/96f7ef3708628d12a147d58496be82ed0bc4e6f2 to include also the possibility to remove the SearchServicesConfig plugin https://github.com/geosolutions-it/geonode-mapstore-client/issues/204

**Comment by giohappy** [comment] 2021-03-04 16:46
@allyoucanmap it would be great to have both in 2.1.x, so we will have it GeoNode 3.2 and our customers are happy to remove the search service configuration button ;)

**Closed** 2022-05-16 08:15 UTC
Labels: bug, MS2 Integration, MapStore, BackportNeeded
