### ISSUE TITLE
Visibility limits problem for the layer on map

### ISSUE THREAD

**Issue by ElenaGallo** [geosolutions-it/geonode-mapstore-client#211] opened 2021-03-03 10:54 UTC
The visibility limits of a layer, set in the settings view, are not saved when the map is saved

**How to Reproduce**
- Open a map on demo.master
- Select a layer on TOC
- Click on Settings
- Click on Display 
- Set the Max and Min values 
- Click on Save
- Click on Burger Menu 
- Click on Save
- Go back to the maps list
- Open again the map

*Current Result*
The visibility limits of a layer is no longer visible on map

**Comment by giohappy** [comment] 2021-03-03 10:58
@ElenaGallo can you please share a link to a map where you tested this?

**Comment by ElenaGallo** [comment] 2021-03-03 11:57
@giohappy [this one](https://master.demo.geonode.org/maps/479/edit)

**Comment by giohappy** [comment] 2021-03-03 14:41
I see the value is set (although it was set the same both for min and max). Probably the issue is that it's not reported inside the input box as expected. Can you confirm?

Example for the min value:

![image](https://user-images.githubusercontent.com/571129/109822077-ebbc5a80-7c36-11eb-8ab0-09877a7bf1d6.png)

**Comment by ElenaGallo** [comment] 2021-03-03 16:09
@giohappy the values are not set, the arrow indicates only the scale at which you are viewing the map at that moment. 
See this video: 

![limite2](https://user-images.githubusercontent.com/56537133/109835070-27f5b800-7c43-11eb-9395-46428acf07db.gif)

**Comment by giohappy** [comment] 2021-03-03 16:12
thanks, my fault.

**Comment by giohappy** [comment] 2021-03-03 16:24
@allyoucanmap now that we have cut 2.1.x if any fix is needed here it will have to be backported on 2.1.x, to be included in GN 3.2

**Comment by allyoucanmap** [comment] 2021-03-05 10:24
fixed in this commit https://github.com/GeoNode/geonode-mapstore-client/commit/b78555f06794d29603ddc84cb851c85d814bc9ea and related to #214

**Comment by ElenaGallo** [comment] 2021-03-05 11:15
@giohappy the test done, the issue is resolved

**Closed** 2021-03-05 11:21 UTC
Labels: BackportNeeded, MS2 Integration, MapStore, bug
